#!/bin/bash

ROOT_DIR=$(cd $(dirname $0)/.. > /dev/null; pwd)
cd $ROOT_DIR

chmod 755 ./scripts/* || exit 1
./scripts/syncheck-all || exit 1

echo "Compiling code and running tests ..."
sbt compile || exit 1
sbt update test || exit 1
