#!/usr/bin/env python
import sys

MAX_LINE_LENGTH = 120

errs = 0
for fname in sys.argv[1:]:
    fd = fname == '-' and sys.stdin or file(fname)
    for no,line in enumerate(fd.readlines()):
        line = line[:-1]
        no += 1
        if '\t' in line:
            errs += 1
            pos = line.index("\t")
            print "%s:%i: tab character found at %i" % (fname,no,pos)
            continue
        if '\r' in line:
            errs += 1
            print "%s:%i: dos carriage return found" % (fname,no)
            continue
        if len(line) > MAX_LINE_LENGTH:
            errs += 1
            print "%s:%i: line too long (%i characters)" % (fname,no,len(line))
            continue
        if line != line.rstrip():
            errs += 1
            print "%s:%i: trailing whitespace found" % (fname,no)
            continue

sys.exit(min(errs, 254))
